name: Feature Request
description: Suggest a new feature or enhancement for SnackbarX
title: "[Feature]: "
labels: ["enhancement", "feature-request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please fill out this form to help us understand your request.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you'd like to see
      placeholder: Add support for custom animations...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: Currently, users cannot...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like to add...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've considered...
    validations:
      required: false

  - type: textarea
    id: api_design
    attributes:
      label: API Design (Optional)
      description: If you have ideas about how the API should look, please share
      render: dart
      placeholder: |
        ```dart
        // Example API usage
        SnackbarX.showCustom(
          message: 'Hello',
          customProperty: value,
        );
        ```
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my project
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple - Minor change or addition
        - Medium - Moderate development effort
        - Complex - Significant changes required
        - I'm not sure
    validations:
      required: false

  - type: textarea
    id: use_case
    attributes:
      label: Use Case Examples
      description: Provide specific examples of how you would use this feature
      placeholder: |
        1. In my app, I need to...
        2. When users perform action X, I want to...
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
      placeholder: Any additional information that might help...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests
          required: true
        - label: This feature would benefit other users, not just my specific use case
          required: true
        - label: I understand this is a voluntary project and there's no guarantee of implementation
          required: true